all::	crash-300px.png sshot-6-300px.png

crash-300px.png:	crash.png
	convert -resize 300x crash.png crash-300px.png

sshot-6-300px.png:	sshot-6.png
	convert -resize 300x sshot-6.png sshot-6-300px.png


