#!/usr/bin/perl

for($if=30; $if<=100; $if+=10) { 
   $if = sprintf("%03d",$if);
   for($t=190; $t<=230; $t+=5) {  
      my($if_) = $if/100;
      print "slicing to cube-$t-$if.gcode\n";
      `slic3r --skirt-distance=4 "--fill-density=$if_" --temperature=$t ../cube10mm.stl -o cube-$t-$if.gcode`
         unless(-f "cube-$t-$if.gcode");
   }
}
